"use client";

import { useState, useTransition, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input, Label, Select, Textarea } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import type { Project } from "@/lib/types";
import { emptyContractClimateParameters, validateContractClimateParameters, type ContractClimateParameters, type ContractClimateResult } from "@/lib/projects/contract-climate";
import { loadContractClimate, saveContractClimatePolicy, calculateContractClimate, saveContractDayAssessment,
  recordContractTimeAdjustment, attachContractClimateToCertificate } from "../contract-climate-actions";

type Bundle=NonNullable<Awaited<ReturnType<typeof loadContractClimate>>["data"]>;
const NO_OPTIONS: [string,string][]=[];
function Field({label,children}:{label:string;children:ReactNode}) {return <label className="block space-y-1 text-xs"><span className="text-[var(--muted)]">{label}</span>{children}</label>;}
function Section({title,children}:{title:string;children:ReactNode}) {return <fieldset className="rounded-lg border border-[var(--border)] p-3"><legend className="px-1 text-xs font-semibold">{title}</legend><div className="grid gap-3 sm:grid-cols-2">{children}</div></fieldset>;}

export function ContractClimateDialog({project}:{project:Project}) {
  const [open,setOpen]=useState(false),[pending,startTransition]=useTransition();
  const [bundle,setBundle]=useState<Bundle|null>(null),[parameters,setParameters]=useState(emptyContractClimateParameters);
  const [tab,setTab]=useState<"parameters"|"calculation"|"history"|"approvals">("parameters");
  const [message,setMessage]=useState<string|null>(null),[dirty,setDirty]=useState(false);
  const [holidaysText,setHolidaysText]=useState("");
  const [from,setFrom]=useState(project.orden_inicio_date??project.start_date??""),[to,setTo]=useState("");
  const [calculation,setCalculation]=useState<ContractClimateResult|null>(null),[certificate,setCertificate]=useState("");
  const [assessment,setAssessment]=useState<{workdayId:string;date:string;impediment:boolean|null;conformity:boolean|null;documentRef:string;notes:string}|null>(null);
  const [approval,setApproval]=useState({days:"",documentRef:"",approvedDate:""});
  const update=<K extends keyof ContractClimateParameters>(key:K,value:ContractClimateParameters[K])=>{setParameters(p=>({...p,[key]:value}));setDirty(true);setMessage(null);};
  const run=(fn:()=>Promise<void>)=>{setMessage(null);startTransition(async()=>{try{await fn();}catch{setMessage("No se pudo completar. Revisá la conexión y reintentá.");}});};
  async function reload(resetForm=false) {
    const response=await loadContractClimate(project.id);
    if(response.error || !response.data){setMessage(response.error??"No se pudo cargar la configuración.");return;}
    setBundle(response.data);
    if(resetForm){const next=response.data.policies[0]?.parameters??{...emptyContractClimateParameters(),startDate:project.orden_inicio_date??project.start_date??"",baseDays:project.plazo_dias??null};setParameters(next);setHolidaysText(next.holidays.join("\n"));setDirty(false);}
  }
  const selectField=(key:keyof ContractClimateParameters,label:string,options:[string,string][]=NO_OPTIONS)=><Field label={label}><Select aria-label={label} disabled={pending} value={String(parameters[key]??"")} onChange={e=>update(key,e.target.value===""?null:e.target.value as never)}><option value="">Sin definir</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</Select></Field>;
  const textField=(key:"label"|"documentRef"|"clauseRef"|"effectiveFrom"|"startDate"|"sourceName"|"stationId",label:string,type="text")=><Field label={label}><Input aria-label={label} type={type} disabled={pending} value={parameters[key]} onChange={e=>update(key,e.target.value)}/></Field>;
  const numberField=(key:"baseDays"|"thresholdMm"|"toleranceDays"|"monthlyCap"|"totalCap",label:string)=><Field label={label}><Input aria-label={label} type="number" min="0" max="10000" step={key==="thresholdMm"||key==="toleranceDays"?"0.01":"1"} disabled={pending} value={parameters[key]??""} placeholder="Sin definir" onChange={e=>update(key,e.target.value===""?null:Number(e.target.value))}/></Field>;
  const booleanField=(key:"includeStart"|"requireEvidence"|"requireCausality"|"requireImpediment"|"requireConformity",label:string)=><Field label={label}><Select aria-label={label} disabled={pending} value={parameters[key]===null?"":parameters[key]?"YES":"NO"} onChange={e=>update(key,e.target.value===""?null:e.target.value==="YES")}><option value="">Sin definir</option><option value="YES">Sí</option><option value="NO">No</option></Select></Field>;
  async function save(status:"DRAFT"|"VALIDATED") {
    const response=await saveContractClimatePolicy(project.id,parameters,status);
    if(response.error){setMessage(response.error);return;}
    setDirty(false);await reload();setMessage(status==="VALIDATED"?`Versión ${response.data?.version} validada. Se aplicará según su vigencia.`:`Borrador ${response.data?.version} guardado. Todavía no se usa para calcular.`);
  }
  async function calculate() {const response=await calculateContractClimate(project.id,from,to);if(response.error){setMessage(response.error);return;}setCalculation(response.data);}
  const issues=validateContractClimateParameters(parameters,true);
  return <Dialog open={open} onOpenChange={value=>{if(pending)return;setOpen(value);if(value)run(()=>reload(!dirty));}}>
    <DialogTrigger asChild><Button size="sm" variant="secondary">Parámetros del PBC</Button></DialogTrigger>
    <DialogContent title="PBC / adendas · parámetros contractuales" className="max-w-4xl">
      <p className="mb-3 text-xs text-[var(--muted)]">{project.name} · Cada guardado crea una versión. El calendario registra hechos; estas reglas determinan qué días admite el contrato.</p>
      <div className="mb-4 flex flex-wrap gap-2" role="tablist" aria-label="Configuración contractual">{([["parameters","Parámetros"],["calculation","Cálculo / certificado"],["history","Versiones"],["approvals","Prórrogas aprobadas"]] as const).map(([key,label])=><Button key={key} type="button" size="sm" role="tab" aria-selected={tab===key} variant={tab===key?"primary":"secondary"} onClick={()=>setTab(key)}>{label}</Button>)}</div>
      {message?<p className="mb-3 rounded-lg border border-[var(--border)] p-3 text-xs" role="status">{message}</p>:null}
      {!bundle?<p className="text-xs">{pending?"Cargando reglas…":"No se pudo cargar el registro del PBC. Reabrí para reintentar."}</p>:<>
      {tab==="parameters"?<div className="space-y-4">
        <Section title="Documento y vigencia">{textField("label","Nombre de la versión")}{textField("documentRef","Referencia del PBC / adenda")}{textField("clauseRef","Cláusula y página")}{textField("effectiveFrom","Vigente desde","date")}</Section>
        <Section title="Plazo y calendario contractual">{textField("startDate","Fecha de inicio contractual","date")}{numberField("baseDays","Plazo base · días")}{selectField("dayBasis","Tipo de plazo",[["CALENDAR","Días corridos"],["WORKING","Días hábiles"]])}{booleanField("includeStart","¿Se cuenta el día inicial?")}
          {parameters.dayBasis==="WORKING"?<div className="sm:col-span-2"><Label>Días laborales</Label><div className="flex flex-wrap gap-3">{["Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"].map((day,index)=><label key={day} className="flex gap-1 text-xs"><input type="checkbox" disabled={pending} checked={parameters.workingWeekdays.includes(index)} onChange={e=>update("workingWeekdays",e.target.checked?[...parameters.workingWeekdays,index]:parameters.workingWeekdays.filter(x=>x!==index))}/>{day}</label>)}</div></div>:null}
          <Field label="Feriados · una fecha AAAA-MM-DD por línea"><Textarea disabled={pending} value={holidaysText} onChange={e=>{setHolidaysText(e.target.value);update("holidays",e.target.value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean));}}/></Field>
        </Section>
        <Section title="Lluvia y evidencia">{numberField("thresholdMm","Umbral de precipitación · mm")}{selectField("thresholdOperator","Comparación del umbral",[["GT","Mayor que (>)"],["GTE","Mayor o igual (≥)"]])}{selectField("rainSource","Fuente de medición exigida",[["EXTERNAL","Meteorológica externa"],["LOCAL","Pluviómetro local"],["EITHER","Cualquiera de las dos"],["NOT_REQUIRED","El PBC no exige medición"]])}{textField("sourceName","Fuente externa exacta · opcional")}{textField("stationId","ID de estación exigida · opcional")}{booleanField("requireEvidence","¿Exige evidencia adjunta?")}{booleanField("requireCausality","¿HH exige vínculo con lluvia anterior?")}{booleanField("requireImpediment","¿Exige impedimento efectivo acreditado?")}{booleanField("requireConformity","¿Exige conformidad de fiscalización?")}</Section>
        <Section title="Jornadas y causas admitidas"><div><Label>Tipos elegibles</Label><div className="flex flex-wrap gap-4">{(["LL","HH","O"] as const).map(code=><label key={code} className="flex gap-1 text-xs"><input type="checkbox" disabled={pending} checked={parameters.eligibleCodes.includes(code)} onChange={e=>update("eligibleCodes",e.target.checked?[...parameters.eligibleCodes,code]:parameters.eligibleCodes.filter(x=>x!==code))}/>{code}</label>)}</div></div>
          <div><Label>Causas O admitidas</Label>{([["TERRAIN_SATURATED","Terreno saturado"],["ACCESS_BLOCKED","Acceso bloqueado"],["FLOODED_EXCAVATION","Excavación inundada"],["UNSAFE_CONDITIONS","Condiciones inseguras"],["MATERIAL_IMPACT","Afectación de materiales"],["OTHER","Otra causa documentada"]] as const).map(([code,label])=><label key={code} className="mb-1 flex gap-1 text-xs"><input type="checkbox" disabled={pending} checked={parameters.otherReasons.includes(code)} onChange={e=>update("otherReasons",e.target.checked?[...parameters.otherReasons,code]:parameters.otherReasons.filter(x=>x!==code))}/>{label}</label>)}</div></Section>
        <Section title="Tolerancias, topes y fórmula">{numberField("toleranceDays","Días de tolerancia · cero debe indicarse")}{selectField("toleranceScope","Aplicar tolerancia por",[["MONTH","Mes calendario"],["CONTRACT","Contrato acumulado"],["PERIOD","Período evaluado / certificado"]])}{selectField("partialMonth","Mes contractual parcial",[["FULL","Tolerancia mensual completa"],["PRORATA","Prorratear por días corridos del mes dentro del plazo base"]])}{selectField("capMode","Límites",[["NONE","Sin topes"],["LIMIT","Aplicar topes indicados"]])}{parameters.capMode==="LIMIT"?<>{numberField("monthlyCap","Tope mensual · días (vacío: no aplica)")}{numberField("totalCap","Tope global · días (vacío: no aplica)")}</>:null}{selectField("rounding","Redondeo de días computables",[["FLOOR","Hacia abajo"],["CEIL","Hacia arriba"],["NEAREST","Al entero más cercano"]])}{selectField("formula","Fórmula contractual",[["EXCESS_ELIGIBLE_DAYS_V1","Días elegibles − tolerancia, luego topes"],["UNSUPPORTED","Otra fórmula del PBC · requiere implementación"]])}
          <Field label="Cláusula / observaciones de fórmula"><Textarea disabled={pending} value={parameters.unsupportedClause} onChange={e=>update("unsupportedClause",e.target.value)}/></Field>
        </Section>
        {issues.length?<details className="text-xs" open><summary>{issues.length} puntos pendientes para validar</summary><ul className="mt-2 list-disc pl-4">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul></details>:<p className="text-xs text-[var(--ok)]">Parámetros completos para la fórmula seleccionada. Revisá que coincidan con las cláusulas del contrato.</p>}
        <div className="flex flex-wrap items-center gap-2"><Button type="button" disabled={pending} variant="secondary" onClick={()=>run(()=>save("DRAFT"))}>Guardar borrador</Button><Button type="button" disabled={pending||issues.length>0} onClick={()=>run(()=>save("VALIDATED"))}>Validar y usar esta versión</Button><span className="text-xs text-[var(--muted)]">{dirty?"Cambios sin guardar":"Las versiones anteriores se conservan"}</span></div>
      </div>:null}
      {tab==="history"?<div className="space-y-2">{bundle.policies.length?bundle.policies.map(policy=><div key={policy.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[var(--border)] p-3 text-xs"><div><strong>V{policy.version} · {policy.parameters.label||"Sin nombre"}</strong><p>{policy.status==="VALIDATED"?"Validada":"Borrador"} · vigente desde {policy.parameters.effectiveFrom||"sin definir"}</p><p className="text-[var(--muted)]">{policy.parameters.documentRef} · {policy.parameters.clauseRef}</p></div><Button size="sm" variant="secondary" disabled={pending} onClick={()=>{setParameters(policy.parameters);setHolidaysText(policy.parameters.holidays.join("\n"));setDirty(false);setTab("parameters");}}>Usar como base de nueva versión</Button></div>):<p className="text-xs">Todavía no hay un PBC registrado. Cargá sus parámetros y guardá el primer borrador.</p>}</div>:null}
      {tab==="calculation"?<div className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-3"><Field label="Período desde"><Input type="date" value={from} disabled={pending} onChange={e=>{setFrom(e.target.value);setCalculation(null);}}/></Field><Field label="Período hasta"><Input type="date" value={to} disabled={pending} onChange={e=>{setTo(e.target.value);setCalculation(null);}}/></Field><div className="flex items-end"><Button disabled={pending||!from||!to} onClick={()=>run(calculate)}>Calcular desde el Libro guardado</Button></div></div>
        <p className="text-xs text-[var(--muted)]">El cálculo usa versiones validadas según fecha. Los cambios sin guardar del calendario no se incluyen. Un día sin clasificar queda pendiente, no se inventa B.</p>
        {calculation?<>
          <div className="rounded-lg border border-[var(--border)] p-3 text-xs"><strong>{calculation.status==="COMPLETE"?"Cálculo completo":calculation.status==="PROVISIONAL"?"Cálculo provisional · faltan datos":"Cálculo bloqueado"}</strong><p className="mt-2">Elegibles del período: {calculation.eligibleDays} · Computables del período: {calculation.computableDays} · Acumulado computable: {calculation.cumulativeComputableDays}</p><p>Vencimiento base: {calculation.baseDueDate??"—"} · Vencimiento con prórrogas aprobadas: {calculation.officialDueDate??"—"}</p><p>Fecha teórica por días climáticos acumulados: {calculation.proposedDueDate??"—"}. Es una estimación para justificar la solicitud; no modifica el vencimiento oficial.</p>{calculation.issues.map(issue=><p key={issue} className="mt-1 text-[var(--warn)]">{issue}</p>)}</div>
          {calculation.groups.length?<div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>Grupo</th><th>Elegibles</th><th>Tolerancia</th><th>Computables</th></tr></thead><tbody>{calculation.groups.map(group=><tr key={group.key}><td>{group.key}</td><td>{group.eligible}</td><td>{group.tolerance}</td><td>{group.computable}</td></tr>)}</tbody></table></div>:null}
          <details className="text-xs" open><summary>Desglose por día · {calculation.dates.length} fechas</summary><div className="mt-2 max-h-64 overflow-auto"><table className="w-full text-left"><thead><tr><th>Fecha</th><th>Tipo</th><th>Resultado / motivo</th><th>Días</th><th/></tr></thead><tbody>{calculation.dates.map(row=><tr key={row.date} className="border-b border-[var(--border)]"><td className="p-1">{row.date}</td><td>{row.code??"—"}</td><td>{row.state==="PENDING"?"Pendiente":row.state==="ELIGIBLE"?"Admitido":"Excluido"}: {row.reason}</td><td>{row.computableDays}</td><td>{row.workdayId?<Button size="sm" variant="secondary" disabled={pending} onClick={()=>setAssessment({workdayId:row.workdayId!,date:row.date,impediment:null,conformity:null,documentRef:"",notes:""})}>Valorar</Button>:null}</td></tr>)}</tbody></table></div></details>
          {assessment?<div className="space-y-3 rounded-lg border border-[var(--border)] p-3"><strong className="text-xs">Valoración contractual · {assessment.date}</strong><div className="grid gap-3 sm:grid-cols-2">{(["impediment","conformity"] as const).map(key=><Field key={key} label={key==="impediment"?"Impedimento efectivo":"Conformidad de fiscalización"}><Select value={assessment[key]===null?"":assessment[key]?"YES":"NO"} disabled={pending} onChange={e=>setAssessment({...assessment,[key]:e.target.value===""?null:e.target.value==="YES"})}><option value="">Sin determinar</option><option value="YES">Sí</option><option value="NO">No</option></Select></Field>)}<Field label="Referencia documental"><Input disabled={pending} value={assessment.documentRef} onChange={e=>setAssessment({...assessment,documentRef:e.target.value})}/></Field><Field label="Notas"><Textarea disabled={pending} value={assessment.notes} onChange={e=>setAssessment({...assessment,notes:e.target.value})}/></Field></div><Button disabled={pending} onClick={()=>run(async()=>{const response=await saveContractDayAssessment(project.id,assessment.workdayId,assessment);if(response.error){setMessage(response.error);return;}setAssessment(null);await calculate();})}>Guardar valoración y recalcular</Button></div>:null}
        </>:null}
        <div className="space-y-2 rounded-lg border border-[var(--border)] p-3"><strong className="text-xs">Anexo del certificado</strong><Select aria-label="Certificado para el anexo" disabled={pending} value={certificate} onChange={e=>{setCertificate(e.target.value);const cert=bundle.certificates.find(c=>c.id===e.target.value);if(cert){setFrom(cert.period_start);setTo(cert.period_end);setCalculation(null);}}}><option value="">Elegí un certificado borrador</option>{bundle.certificates.filter(c=>c.status==="BORRADOR").map(c=><option key={c.id} value={c.id}>Nº {c.numero} · {c.period_start} a {c.period_end}</option>)}</Select><p className="text-xs text-[var(--muted)]">Se recalcula el período del certificado en el servidor y se conserva una copia inmutable de reglas, hechos y resultado. No altera importes ni aprueba prórrogas.</p><Button disabled={pending||!certificate} onClick={()=>run(async()=>{const response=await attachContractClimateToCertificate(project.id,certificate);setMessage(response.error??"Anexo completo asociado. El PDF del certificado incluirá esta copia.");})}>Calcular y asociar anexo al certificado</Button></div>
      </div>:null}
      {tab==="approvals"?<div className="space-y-4"><p className="text-xs">Registrá únicamente prórrogas ya aprobadas documentalmente. Los días calculados no se convierten en aprobaciones.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Días reconocidos"><Input type="number" min="1" step="1" disabled={pending} value={approval.days} onChange={e=>setApproval({...approval,days:e.target.value})}/></Field><Field label="Resolución / adenda aprobada"><Input disabled={pending} value={approval.documentRef} onChange={e=>setApproval({...approval,documentRef:e.target.value})}/></Field><Field label="Fecha de aprobación"><Input type="date" disabled={pending} value={approval.approvedDate} onChange={e=>setApproval({...approval,approvedDate:e.target.value})}/></Field></div><Button disabled={pending||!approval.days||!approval.documentRef||!approval.approvedDate} onClick={()=>run(async()=>{const response=await recordContractTimeAdjustment(project.id,{...approval,days:Number(approval.days)});if(response.error){setMessage(response.error);return;}setApproval({days:"",documentRef:"",approvedDate:""});await reload();setCalculation(null);setMessage("Prórroga documentada registrada.");})}>Registrar prórroga aprobada</Button>{bundle.adjustments.map(a=><p key={a.id} className="text-xs">{a.approved_date} · {a.document_ref} · {a.days} días</p>)}</div>:null}
      </>}
      <div className="mt-4 flex justify-end"><Button variant="secondary" disabled={pending} onClick={()=>setOpen(false)}>Cerrar</Button></div>
    </DialogContent>
  </Dialog>;
}
