-- Read-only structural inventory; no application data is selected.
SET search_path = public, extensions, pg_catalog;
WITH app_ns AS (SELECT oid,nspname FROM pg_namespace WHERE nspname IN ('public','private')),
rels AS (SELECT c.*,n.nspname FROM pg_class c JOIN app_ns n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p','v','m','S','f')),
funcs AS (SELECT p.*,n.nspname FROM pg_proc p JOIN app_ns n ON n.oid=p.pronamespace WHERE p.prokind IN ('f','p')),
objects AS (
 SELECT 'relation' AS kind,format('%I.%I',c.nspname,c.relname) AS name,c.relowner AS owner,coalesce(c.relacl,acldefault(CASE WHEN c.relkind='S' THEN 's'::"char" ELSE 'r'::"char" END,c.relowner)) AS acl FROM rels c
 UNION ALL SELECT 'function',format('%I.%I(%s)',p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),p.proowner,coalesce(p.proacl,acldefault('f',p.proowner)) FROM funcs p
 UNION ALL SELECT 'schema',n.nspname,n.nspowner,coalesce(n.nspacl,acldefault('n',n.nspowner)) FROM pg_namespace n WHERE n.nspname IN ('public','private')
 UNION ALL SELECT 'type',format('%I.%I',n.nspname,t.typname),t.typowner,coalesce(t.typacl,acldefault('T',t.typowner)) FROM pg_type t JOIN app_ns n ON n.oid=t.typnamespace WHERE t.typtype IN ('e','d')
),
inventory AS (
SELECT jsonb_build_object(
 'relations',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I',nspname,relname),'kind',relkind,'persistence',relpersistence,'rls',relrowsecurity,'force_rls',relforcerowsecurity,'options',reloptions,'owner',pg_get_userbyid(relowner),'replica_identity',relreplident,'partition',CASE WHEN relispartition THEN pg_get_expr(relpartbound,oid) ELSE NULL END) ORDER BY nspname,relname),'[]'::jsonb) FROM rels),
 'columns',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I.%I',c.nspname,c.relname,a.attname),'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'collation',CASE WHEN a.attcollation<>0 THEN a.attcollation::regcollation::text ELSE NULL END,'storage',a.attstorage,'statistics',a.attstattarget) ORDER BY c.nspname,c.relname,a.attnum),'[]'::jsonb) FROM rels c JOIN pg_attribute a ON a.attrelid=c.oid LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum WHERE a.attnum>0 AND NOT a.attisdropped AND c.relkind<>'S'),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I.%I',c.nspname,c.relname,x.conname),'type',x.contype,'definition',pg_get_constraintdef(x.oid,false),'validated',x.convalidated,'deferrable',x.condeferrable,'deferred',x.condeferred) ORDER BY c.nspname,c.relname,x.conname),'[]'::jsonb) FROM rels c JOIN pg_constraint x ON x.conrelid=c.oid),
 'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I',c.nspname,i.relname),'definition',pg_get_indexdef(i.oid),'valid',x.indisvalid,'ready',x.indisready,'clustered',x.indisclustered,'replica_identity',x.indisreplident) ORDER BY c.nspname,i.relname),'[]'::jsonb) FROM rels c JOIN pg_index x ON x.indrelid=c.oid JOIN pg_class i ON i.oid=x.indexrelid),
 'functions',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I(%s)',p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner)) ORDER BY p.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) FROM funcs p),
 'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I.%I',c.nspname,c.relname,t.tgname),'definition',pg_get_triggerdef(t.oid,false),'enabled',t.tgenabled) ORDER BY c.nspname,c.relname,t.tgname),'[]'::jsonb) FROM rels c JOIN pg_trigger t ON t.tgrelid=c.oid WHERE NOT t.tgisinternal),
 'policies',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I.%I',schemaname,tablename,policyname),'permissive',permissive,'roles',roles,'command',cmd,'using',qual,'check',with_check) ORDER BY schemaname,tablename,policyname),'[]'::jsonb) FROM pg_policies WHERE schemaname IN ('public','private','storage')),
 'views',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I',nspname,relname),'kind',relkind,'definition',pg_get_viewdef(oid,false),'options',reloptions) ORDER BY nspname,relname),'[]'::jsonb) FROM rels WHERE relkind IN ('v','m')),
 'types',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I',n.nspname,t.typname),'kind',t.typtype,'base',format_type(t.typbasetype,t.typtypmod),'not_null',t.typnotnull,'default',t.typdefault,'labels',(SELECT jsonb_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_enum e WHERE e.enumtypid=t.oid)) ORDER BY n.nspname,t.typname),'[]'::jsonb) FROM pg_type t JOIN app_ns n ON n.oid=t.typnamespace WHERE t.typtype IN ('e','d')),
 'sequences',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',format('%I.%I',c.nspname,c.relname),'type',format_type(s.seqtypid,NULL),'start',s.seqstart::text,'increment',s.seqincrement::text,'max',s.seqmax::text,'min',s.seqmin::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'owned_by',(SELECT format('%I.%I.%I',n.nspname,r.relname,a.attname) FROM pg_depend d JOIN pg_class r ON r.oid=d.refobjid JOIN pg_namespace n ON n.oid=r.relnamespace JOIN pg_attribute a ON a.attrelid=r.oid AND a.attnum=d.refobjsubid WHERE d.classid='pg_class'::regclass AND d.objid=c.oid AND d.refclassid='pg_class'::regclass AND d.deptype IN ('a','i') LIMIT 1)) ORDER BY c.nspname,c.relname),'[]'::jsonb) FROM rels c JOIN pg_sequence s ON s.seqrelid=c.oid),
 'grants',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',o.kind||':'||o.name||':'||CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END||':'||a.privilege_type,'grantable',a.is_grantable) ORDER BY o.kind,o.name,a.grantee,a.privilege_type),'[]'::jsonb) FROM objects o CROSS JOIN LATERAL aclexplode(o.acl) a),
 'default_privileges',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',pg_get_userbyid(d.defaclrole)||':'||n.nspname||':'||d.defaclobjtype::text||':'||CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END||':'||a.privilege_type,'grantable',a.is_grantable) ORDER BY n.nspname,d.defaclrole,d.defaclobjtype,a.grantee,a.privilege_type),'[]'::jsonb) FROM pg_default_acl d JOIN app_ns n ON n.oid=d.defaclnamespace CROSS JOIN LATERAL aclexplode(d.defaclacl) a),
 'publications',(SELECT coalesce(jsonb_agg(jsonb_build_object('key',pubname||':'||schemaname||'.'||tablename,'columns',attnames,'filter',rowfilter) ORDER BY pubname,schemaname,tablename),'[]'::jsonb) FROM pg_publication_tables WHERE schemaname IN ('public','private')),
 'extensions',(SELECT jsonb_agg(jsonb_build_object('key',e.extname,'schema',n.nspname,'version',e.extversion) ORDER BY e.extname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace)
) AS inventory
) SELECT inventory FROM inventory;

