// Synthetic fixture ONLY on the explicitly allowlisted Batch04 Preview.
// Run from the worktree after build + `next start -p 3444`.
import fs from "node:fs";
import { randomUUID, createHash } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import pg from "pg";
import { chromium } from "@playwright/test";

const ref="xddlzgjwufskgasomval";
const config=JSON.parse(fs.readFileSync(".env.preview-private.json","utf8").replace(/^\uFEFF/,""));
if(config.SUPABASE_URL!==`https://${ref}.supabase.co`)throw Error("Only isolated Batch04 Preview is allowed");
const admin=createClient(config.SUPABASE_URL,config.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
const sql=new pg.Client({connectionString:config.POSTGRES_URL_NON_POOLING,ssl:{rejectUnauthorized:false}});
await sql.connect();
const company=randomUUID(),tender=randomUUID(),product=randomUUID(),provider=randomUUID();
const email=`batch04-ui-${randomUUID()}@example.invalid`,password=`A1!${randomUUID()}`;
const {data:user,error:authError}=await admin.auth.admin.createUser({email,password,email_confirm:true});
if(authError)throw authError;
const actor=user.user.id;
await sql.query("insert into public.empresas(id,nombre,plan) values($1,'Batch04 UI synthetic audit','caterpillar')",[company]);
await sql.query("insert into public.profiles(id,email,full_name,empresa_id,role,active) values($1,$2,'Batch04 UI test',$3,'admin',true) on conflict(id) do update set empresa_id=excluded.empresa_id,role='admin',active=true",[actor,email,company]);
await sql.query("insert into public.licitaciones(id,empresa_id,dncp_nro,ocid,titulo) values($1,$2,$3,$3,'Batch04 UI synthetic tender')",[tender,company,`batch04-ui-${tender}`]);
await sql.query("insert into public.licitacion_items(licitacion_id,empresa_id,descripcion,cantidad,unidad) values($1,$2,'Synthetic measured wall',10,'m2')",[tender,company]);
await sql.query("insert into public.productos(id,empresa_id,nombre,unidad,costo_promedio) values($1,$2,'Batch04 material','u',100)",[product,company]);
await sql.query("insert into public.providers(id,empresa_id,name) values($1,$2,'Batch04 supplier')",[provider,company]);
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on("pageerror",e=>errors.push(e.message));const consoleErrors=[];page.on("console",msg=>{if(msg.type()==="error"){const url=new URL(msg.location().url||"http://localhost");consoleErrors.push({message:msg.text(),path:url.pathname});}});
const failedResponses=[];page.on("response",async response=>{if(response.status()>=400){const url=new URL(response.url());let detail="";try{const body=await response.json();detail=JSON.stringify({code:body.code,message:body.message,error:body.error});}catch{}failedResponses.push({path:url.pathname,status:response.status(),detail});}});
page.on("dialog",dialog=>dialog.accept());
await page.goto("http://localhost:3444/login");
await page.locator("#email").fill(email);await page.locator("#password").fill(password);
await page.getByRole("button",{name:"Ingresar",exact:true}).click();
await page.waitForURL(url=>!url.pathname.includes("login"),{timeout:30000});
await page.goto(`http://localhost:3444/licitaciones/${tender}/prebid`);
await page.getByTestId("prebid-workspace").waitFor();
await page.getByRole("button",{name:"Importar ítems de licitación"}).click();
await page.getByRole("cell",{name:"Synthetic measured wall"}).waitFor();
await page.getByRole("button",{name:"APU",exact:true}).last().click();
await page.getByLabel("Consumo por unidad").fill("2");
await page.getByRole("button",{name:"Guardar APU",exact:true}).click();
await page.getByRole("button",{name:"Costeo y evidencia",exact:true}).click();
await page.getByText("Precio para costeo:",{exact:false}).waitFor();
await page.getByLabel("Batch04 supplier",{exact:false}).check();
await page.getByRole("button",{name:"COTIZAR · COST_DISCOVERY",exact:true}).click();
await page.getByRole("heading",{name:"RFQs con provenance de licitación"}).waitFor();
await page.waitForFunction(()=>document.body.innerText.includes("ofertas y comparación"));
const {rows:[rfq]}=await sql.query("select id from public.rfqs where tender_id=$1",[tender]);
const {rows:[invitation]}=await sql.query("select id,token from public.rfq_providers where rfq_id=$1",[rfq.id]);
const {rows:[item]}=await sql.query("select id from public.rfq_items where rfq_id=$1",[rfq.id]);
const path=`${invitation.id}/${randomUUID()}.pdf`;
const document=Buffer.from("%PDF-1.4\n% Batch04 synthetic fixture\n%%EOF");
const upload=await admin.storage.from("quote-pdfs").upload(path,document,{contentType:"application/pdf"});
if(upload.error)throw upload.error;
const {rows:[attachment]}=await sql.query("insert into public.attachments(empresa_id,rfq_provider_id,bucket,path,file_name,original_sha256) values($1,$2,'quote-pdfs',$3,'synthetic.pdf',$4) returning id",[company,invitation.id,path,createHash('sha256').update(document).digest('hex')]);
const submit=await admin.rpc("rfq_submit_version",{p_token:invitation.token,p_offer:{valid_until:new Date(Date.now()+86400000*7).toISOString(),freight:0,payment_terms:"30 days",budget_number:"UI-1",currency:"PYG",invoice_available:true,vat_included:true},p_items:[{rfq_item_id:item.id,precio_unitario:73,available_quantity:20,tax_rate:10,lead_time_days:2}],p_attachment_id:attachment.id,p_actor_id:actor});
if(submit.error)throw submit.error;
await page.reload();await page.getByRole("button",{name:"Costeo y evidencia",exact:true}).click();
await page.getByRole("button",{name:"Adoptar precio",exact:true}).click();
await page.waitForFunction(()=>document.body.innerText.includes("adoptado por humano"));
await page.getByRole("button",{name:"Presupuesto / Oferta",exact:true}).click();
await page.getByLabel('Indirectos modo',{exact:true}).selectOption('FIXED');
await page.getByLabel('Indirectos monto PYG',{exact:true}).fill('100');
await page.getByLabel('Financiacion modo',{exact:true}).selectOption('FIXED');
await page.getByLabel('Financiacion monto PYG',{exact:true}).fill('50');
await page.getByLabel('Riesgo %',{exact:true}).fill('5');
// V1 opens as a reproducible named line; new concepts remain free text.
await page.getByLabel('Gastos generales (V1) %',{exact:true}).fill('2');
await page.getByRole('button',{name:'Agregar gasto general',exact:true}).click();
await page.getByLabel(/^Concepto /).last().fill('Oficina de obra');
await page.getByLabel('Oficina de obra monto PYG',{exact:true}).fill('40');
await page.getByRole('button',{name:'Agregar gasto general',exact:true}).click();
await page.getByLabel(/^Concepto /).last().fill('Seguros');
await page.getByLabel('Seguros modo',{exact:true}).selectOption('PERCENT');
await page.getByLabel('Seguros %',{exact:true}).fill('1');
await page.getByLabel('Margen sobre venta %',{exact:true}).fill('20');
await page.getByRole('button',{name:'Guardar composicion',exact:true}).click();
await page.waitForFunction(()=>document.body.innerText.includes('2.209 PYG'));
fs.mkdirSync('.worktrees',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'.worktrees/batch04-browser-composition.png',fullPage:true});
await page.getByRole("button",{name:"Guardar versión",exact:true}).click();
await page.getByRole("button",{name:"PRESENTAR",exact:true}).click();
await page.waitForFunction(()=>document.body.innerText.includes("Snapshot comercial conservado"));
const {rows:[saved]}=await sql.query("select monto_total, v.snapshot from public.licitacion_ofertas o join public.licitacion_oferta_versions v on v.id=o.submitted_version_id where o.licitacion_id=$1",[tender]);
if(Number(saved.monto_total)!==2208.5||saved.snapshot.offerAmount!==2208.5)throw Error('Server canonical offer mismatch');
if(saved.snapshot.facts.settings.schemaVersion!==2||saved.snapshot.facts.settings.generalItems.length!==3)throw Error('Itemized V2 settings not preserved');
const browserClient=createClient(config.SUPABASE_URL,config.SUPABASE_ANON_KEY,{auth:{persistSession:false}});
const login=await browserClient.auth.signInWithPassword({email,password});if(login.error)throw login.error;
const blocked=await browserClient.rpc('prebid_save_version',{p_tender_id:tender,p_present:true,p_expected_hash:'not-used',p_offer_amount:999999});
if(!blocked.error||blocked.error.code!=='42501')throw Error('Authenticated RPC boundary exposed');
await browserClient.auth.signOut({scope:"local"});
await page.getByRole("button",{name:"Versiones y resultado",exact:true}).click();
await page.getByLabel("Monto adjudicado confirmado",{exact:false}).fill("2100");
await page.getByRole("button",{name:"Confirmar resultado",exact:true}).click();
await page.getByText("READY FOR PROJECT HANDOFF",{exact:false}).waitFor();
fs.mkdirSync(".worktrees",{recursive:true});await page.screenshot({path:".worktrees/batch04-browser-winning.png",fullPage:true});
await page.getByRole("button",{name:"Cómputo",exact:true}).click();
if(!(await page.getByRole("button",{name:"Agregar partida",exact:true}).isDisabled()))throw Error("Winning history writable");
const {rows:[count]}=await sql.query("select count(*)::int as n from public.projects where empresa_id=$1",[company]);
if(count.n!==0)throw Error("Synthetic project created");
// Exact legacy Preview-only exception: baseline schema does not replay Storage
// bucket data, and the unchanged sidebar requests the optional branding logo.
const legacyResources=failedResponses.filter(r=>r.path==='/storage/v1/object/public/branding/current-logo'&&r.status===400&&r.detail.includes('NoSuchBucket'));
const unexpectedResources=failedResponses.filter(r=>!legacyResources.includes(r));
const unexpectedConsole=consoleErrors.filter(e=>!(e.path==='/storage/v1/object/public/branding/current-logo'&&e.message.includes('400')&&legacyResources.length));
if(errors.length||unexpectedResources.length||unexpectedConsole.length)throw Error(JSON.stringify({pageErrors:errors,unexpectedResources,unexpectedConsole}));
console.log(JSON.stringify({status:"PASS",preview:ref,tenderId:tender,companyId:company,projectCount:count.n,offerAmount:2208.5,directRpcTamper:'42501 REJECTED',generalConcepts:3,legacyResources,unexpectedConsole,flow:"Cómputo → APU → COST_DISCOVERY → real DB quote adoption → offer composition → version → PRESENTADA → GANADA → immutable winning handoff",browserErrors:errors}));
await browser.close();await sql.end();
